#ifndef CONFIG_TANK_LIGHT_H
#define CONFIG_TANK_LIGHT_H


#define TANK_PLAYER_LIGHT_HP													70
#define TANK_PLAYER_LIGHT_ROTATE_DELAY								200
#define TANK_PLAYER_LIGHT_MOVE_DELAY_MIN							50
#define TANK_PLAYER_LIGHT_MOVE_DELAY_MAX							7
#define	TANK_PLAYER_LIGHT_ACCELERATION_DELAY					10
#define	TANK_PLAYER_LIGHT_ACCELERATION_SPEED					1
#define TANK_PLAYER_LIGHT_CONTROL_DELAY_ANOTHER				15					//	for pause for another control
#define TANK_PLAYER_LIGHT_ATACK_SPEED									600

#define TANK_PLAYER_LIGHT_BULLET_STEP									3						// 1, 3, 9, 27 or 27/x
#define TANK_PLAYER_LIGHT_BULLET_SPEED								9
#define TANK_PLAYER_LIGHT_BULLET_LIFE_TIME						500


#endif