#ifndef CONFIG_TANK_HEAVY_H
#define CONFIG_TANK_HEAVY_H


#define TANK_PLAYER_HEAVY_HP													150
#define TANK_PLAYER_HEAVY_ROTATE_DELAY								500
#define TANK_PLAYER_HEAVY_MOVE_DELAY_MIN							80
#define TANK_PLAYER_HEAVY_MOVE_DELAY_MAX							15
#define	TANK_PLAYER_HEAVY_ACCELERATION_DELAY					25
#define	TANK_PLAYER_HEAVY_ACCELERATION_SPEED					1
#define TANK_PLAYER_HEAVY_CONTROL_DELAY_ANOTHER				25					//	for pause for another control
#define TANK_PLAYER_HEAVY_ATACK_SPEED									1200

#define TANK_PLAYER_HEAVY_BULLET_STEP									3						// 1, 3, 9, 27 or 27/x
#define TANK_PLAYER_HEAVY_BULLET_SPEED								11
#define TANK_PLAYER_HEAVY_BULLET_LIFE_TIME						900


#endif
