#ifndef CONFIG_TANK_BALANCE_H
#define CONFIG_TANK_BALANCE_H


#define TANK_PLAYER_BALANCE_HP													100
#define TANK_PLAYER_BALANCE_ROTATE_DELAY								400
#define TANK_PLAYER_BALANCE_MOVE_DELAY_MIN							70
#define TANK_PLAYER_BALANCE_MOVE_DELAY_MAX							10
#define	TANK_PLAYER_BALANCE_ACCELERATION_DELAY					20
#define	TANK_PLAYER_BALANCE_ACCELERATION_SPEED					1
#define TANK_PLAYER_BALANCE_CONTROL_DELAY_ANOTHER				15					//	for pause for another control
#define TANK_PLAYER_BALANCE_ATACK_SPEED									800

#define TANK_PLAYER_BALANCE_BULLET_STEP									3						// 1, 3, 9, 27 or 27/x
#define TANK_PLAYER_BALANCE_BULLET_SPEED								10
#define TANK_PLAYER_BALANCE_BULLET_LIFE_TIME						700


#endif